#############################################################################
# Makefile for building: GUItest
# Generated by qmake (2.01a) (Qt 4.8.1) on: Thu Nov 6 22:11:21 2014
# Project:  GUItest.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile GUItest.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = GUImain.cpp \
		login.cpp \
		Movie.cpp \
		Netflix.cpp \
		newUserClass.cpp \
		NoSuchElementException.cpp \
		User.cpp moc_login.cpp \
		moc_newUserClass.cpp
OBJECTS       = GUImain.o \
		login.o \
		Movie.o \
		Netflix.o \
		newUserClass.o \
		NoSuchElementException.o \
		User.o \
		moc_login.o \
		moc_newUserClass.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		GUItest.pro
QMAKE_TARGET  = GUItest
DESTDIR       = 
TARGET        = GUItest

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GUItest.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile GUItest.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile GUItest.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/GUItest1.0.0 || $(MKDIR) .tmp/GUItest1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/GUItest1.0.0/ && $(COPY_FILE) --parents login.h Map.h MapImpl.h Movie.h Netflix.h newUserClass.h NoSuchElementException.h Queue.h QueueImpl.h Set.h SetImpl.h User.h .tmp/GUItest1.0.0/ && $(COPY_FILE) --parents GUImain.cpp login.cpp Movie.cpp Netflix.cpp newUserClass.cpp NoSuchElementException.cpp User.cpp .tmp/GUItest1.0.0/ && (cd `dirname .tmp/GUItest1.0.0` && $(TAR) GUItest1.0.0.tar GUItest1.0.0 && $(COMPRESS) GUItest1.0.0.tar) && $(MOVE) `dirname .tmp/GUItest1.0.0`/GUItest1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/GUItest1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_login.cpp moc_newUserClass.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_login.cpp moc_newUserClass.cpp
moc_login.cpp: Netflix.h \
		User.h \
		Movie.h \
		Set.h \
		Map.h \
		MapImpl.h \
		NoSuchElementException.h \
		SetImpl.h \
		Queue.h \
		QueueImpl.h \
		login.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) login.h -o moc_login.cpp

moc_newUserClass.cpp: newUserClass.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) newUserClass.h -o moc_newUserClass.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

GUImain.o: GUImain.cpp Netflix.h \
		User.h \
		Movie.h \
		Set.h \
		Map.h \
		MapImpl.h \
		NoSuchElementException.h \
		SetImpl.h \
		Queue.h \
		QueueImpl.h \
		login.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GUImain.o GUImain.cpp

login.o: login.cpp login.h \
		Netflix.h \
		User.h \
		Movie.h \
		Set.h \
		Map.h \
		MapImpl.h \
		NoSuchElementException.h \
		SetImpl.h \
		Queue.h \
		QueueImpl.h \
		newUserClass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o login.cpp

Movie.o: Movie.cpp Movie.h \
		Set.h \
		Map.h \
		MapImpl.h \
		NoSuchElementException.h \
		SetImpl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Movie.o Movie.cpp

Netflix.o: Netflix.cpp Netflix.h \
		User.h \
		Movie.h \
		Set.h \
		Map.h \
		MapImpl.h \
		NoSuchElementException.h \
		SetImpl.h \
		Queue.h \
		QueueImpl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Netflix.o Netflix.cpp

newUserClass.o: newUserClass.cpp newUserClass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newUserClass.o newUserClass.cpp

NoSuchElementException.o: NoSuchElementException.cpp NoSuchElementException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NoSuchElementException.o NoSuchElementException.cpp

User.o: User.cpp User.h \
		Movie.h \
		Set.h \
		Map.h \
		MapImpl.h \
		NoSuchElementException.h \
		SetImpl.h \
		Queue.h \
		QueueImpl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o User.o User.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_newUserClass.o: moc_newUserClass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newUserClass.o moc_newUserClass.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

